extensions:
    pcmt-reference-data-import-edit:
        module: pim/form/common/edit-form

    pcmt-reference-data-import-edit-main-image:
        module: pim/form/common/main-image
        parent: pcmt-reference-data-import-edit
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustrations/ImportXLSX.svg

    pcmt-reference-data-import-edit-user-navigation:
        module: pim/menu/user-navigation
        parent: pcmt-reference-data-import-edit
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pcmt-reference-data-import-edit-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pcmt-reference-data-import-edit
        targetZone: breadcrumbs
        config:
            tab: pim-menu-imports

    pcmt-reference-data-import-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: pcmt-reference-data-import-edit
        position: 1000

    pcmt-reference-data-import-edit-tabs:
        module: pim/form/common/form-tabs
        parent: pcmt-reference-data-import-edit
        targetZone: content
        position: 100

    pcmt-reference-data-import-edit-properties:
        module: pim/job/common/edit/properties
        parent: pcmt-reference-data-import-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_common.properties
            tabCode: pim-job-instance-properties

    pcmt-reference-data-import-edit-history:
        module: pim/common/tab/history
        parent: pcmt-reference-data-import-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_import_profile_history
        position: 130
        config:
            class: Akeneo\Tool\Component\Batch\Model\JobInstance
            title: pim_common.history
            tabCode: pim-job-instance-history

    pcmt-reference-data-import-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: pcmt-reference-data-import-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_common.code
            readOnly: true

    pcmt-reference-data-import-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: pcmt-reference-data-import-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_common.label
            readOnly: false

    pcmt-reference-data-import-edit-label:
        module: pim/job/common/edit/label
        parent: pcmt-reference-data-import-edit
        targetZone: title
        position: 100

    pcmt-reference-data-import-edit-meta:
        module: pim/job/common/edit/meta
        parent: pcmt-reference-data-import-edit
        targetZone: meta
        position: 100

    pcmt-reference-data-import-edit-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: pcmt-reference-data-import-edit
        targetZone: buttons
        position: 50

    pcmt-reference-data-import-edit-delete:
        module: pim/job/import/edit/delete
        parent: pcmt-reference-data-import-edit-secondary-actions
        targetZone: secondary-actions
        aclResourceId: pim_importexport_import_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.import_profile
                content: pim_common.confirm_deletion
                success: pim_import_export.entity.job_instance.flash.delete.success
                failed: error.removing.job_instance
            redirect: pim_importexport_import_profile_index

    pcmt-reference-data-import-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: pcmt-reference-data-import-edit
        targetZone: buttons
        position: 120

    pcmt-reference-data-import-edit-save:
        module: pim/job-instance-import-edit-form/save
        parent: pcmt-reference-data-import-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_import_profile_show

    pcmt-reference-data-import-edit-state:
        module: pim/form/common/state
        parent: pcmt-reference-data-import-edit
        targetZone: state
        position: 900
        config:
            entity: pim_import_export.entity.job_instance.label

    pcmt-reference-data-import-edit-validation:
        module: pim/job/common/edit/validation
        parent: pcmt-reference-data-import-edit
