extensions:
    pcmt-reference-data-import-show:
        module: pim/form/common/edit-form

    pcmt-reference-data-import-show-main-image:
        module: pim/form/common/main-image
        parent: pcmt-reference-data-import-show
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustrations/ImportXLSX.svg

    pcmt-reference-data-import-show-user-navigation:
        module: pim/menu/user-navigation
        parent: pcmt-reference-data-import-show
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pcmt-reference-data-import-show-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pcmt-reference-data-import-show
        targetZone: breadcrumbs
        config:
            tab: pim-menu-imports

    pcmt-reference-data-import-show-switcher:
        module: pim/job-instance/import/switcher
        parent: pcmt-reference-data-import-show
        position: 0
        targetZone: meta

    pcmt-reference-data-import-show-upload-switcher-item:
        module: pim/job-instance/import/switcher-item
        parent: pcmt-reference-data-import-show
        targetZone: content
        aclResourceId: pim_importexport_import_profile_launch
        position: 50
        config:
            allowedKey: uploadAllowed
            label: pim_import_export.form.job_instance.button.import.upload_file
            hideForCloudEdition: false

    pcmt-reference-data-import-show-upload:
        module: pim/job/common/edit/upload
        parent: pcmt-reference-data-import-show-upload-switcher-item
        position: 50
        config:
            type: xlsx

    pcmt-reference-data-import-show-upload-button:
        module: pim/job/common/edit/upload-launch
        parent: pcmt-reference-data-import-show-upload-switcher-item
        position: 60
        config:
            label: pim_import_export.form.job_instance.button.import.upload
            route: pim_enrich_job_instance_rest_import_launch
            identifier:
                path: code
                name: code

    pcmt-reference-data-import-show-launch-switcher-item:
        module: pim/job-instance/import/switcher-item
        parent: pcmt-reference-data-import-show
        targetZone: content
        aclResourceId: pim_importexport_import_profile_launch
        position: 40
        config:
            label: pcmt_simple_job.form.job_instance.button.job.switcher
            hideForCloudEdition: true

    pcmt-reference-data-import-show-import-button:
        module: pim/job/common/edit/launch
        parent: pcmt-reference-data-import-show-launch-switcher-item
        config:
            label: pcmt_simple_job.form.job_instance.button.job.launch
            route: pim_enrich_job_instance_rest_import_launch
            identifier:
                path: code
                name: code

    pcmt-reference-data-import-show-subsection:
        module: pim/form/common/subsection
        parent: pcmt-reference-data-import-show
        targetZone: content
        config:
            title: pim_import_export.form.job_instance.subsection.last_executions

    pcmt-reference-data-import-show-grid:
        module: pim/job/common/grid
        parent: pcmt-reference-data-import-show-subsection
        position: 1000
        targetZone: content
        config:
            alias: last-import-executions-grid
            metadata:
                jobType: import

    pcmt-reference-data-import-show-label:
        module: pim/job/common/edit/label
        parent: pcmt-reference-data-import-show
        targetZone: title
        position: 100

    pcmt-reference-data-import-show-edit:
        module: pim/common/redirect
        parent: pcmt-reference-data-import-show
        targetZone: buttons
        position: 100
        aclResourceId: pim_importexport_import_profile_edit
        config:
            label: pim_common.edit
            route: pim_importexport_import_profile_edit
            buttonClass: AknButton AknButton--action
            identifier:
                path: code
                name: code
