######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

extensions:
    pcmt-product-drafts-index:
        module: pim/common/simple-view
        targetZone: self
        config:
            template: pim/template/common/default-template

    pcmt-product-drafts-index-user-navigation:
        module: pim/menu/user-navigation
        parent: pcmt-product-drafts-index
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pcmt-product-drafts-index-title:
        module: pcmt/draft/common/title
        parent: pcmt-product-drafts-index
        targetZone: title
        config:
            title: pcmt_core.drafts_list.page_title.index

    pcmt-product-drafts-index-grid-container:
        module: pim/common/simple-view
        parent: pcmt-product-drafts-index
        targetZone: content
        config:
            template: pim/template/form/index/index

    pcmt-product-drafts-index-content:
        module: pcmt/draft/list
        parent: pcmt-product-drafts-index-grid-container
        position: 1000
        config:
            template: pcmt/product/template/draft-list

    pcmt-product-drafts-index-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pcmt-product-drafts-index
        targetZone: breadcrumbs
        config:
            tab: pim-menu-activity
            item: pcmt-product-drafts-list-sub-element

    pcmt-product-drafts-index-pagination:
        module: pcmt/draft/draft-pagination
        parent: pcmt-product-drafts-index-grid-container
        targetZone: toolbar

    pcmt-product-drafts-index-filters:
        module: pcmt/draft/filters
        parent: pcmt-product-drafts-index-grid-container
        targetZone: filters

    pcmt-pictogram-index-mass-actions:
        module: pcmt/draft/mass-actions
        parent: pcmt-product-drafts-index
        targetZone: bottom-panel
        config:
            label: pim_datagrid.mass_action.selected.product

    pcmt-product-drafts-actions-panel:
        module: pcmt/draft/actions-panel
        parent: pcmt-pictogram-index-mass-actions
        targetZone: actions-panel