######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

version: "3.5"
services:
  fpm:
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome-debug
    container_name: selenium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - '4444:4444'
      - '5900:5900'