######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

extensions:
#   Tab in create Attribute
    pim-attribute-create-form-description-tab:
        module: pim/common/tab
        parent: pim-attribute-create-form-form-tabs
        targetZone: container
        position: 120
        config:
            label: pim_enrich.form.attribute.tab.descriptions.title
#   Connection between tab and content
    pim-attribute-create-form-description-container:
        module: pim/common/simple-view
        parent: pim-attribute-create-form-description-tab
        targetZone: self
        position: 110
        config:
            template: pim/template/common/form-container
#   Content of the tab
    pim-attribute-create-form-description-translation:
        module: dnd/attribute-edit-form/descriptions/translation
        parent: pim-attribute-create-form-description-container
        targetZone: form-container
        position: 110
