services:
    pim_enrich.event_listener.association_product_model_draft_grid_before_listener:
        class: '%pim_datagrid.event_listener.configure_product_grid_listener.class%'
        arguments:
            - '@pim_datagrid.datagrid.configuration.product_model.context_configurator'
            - '@pim_datagrid.datagrid.configuration.product.columns_configurator'
            - '@pim_datagrid.datagrid.configuration.product.filters_configurator'
            - '@pim_datagrid.datagrid.configuration.product.sorters_configurator'
            - '@pim_datagrid.datagrid.configuration.product.selected_attributes_configurator'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before.association-product-model-draft-grid, method: buildBefore }

    pim_enrich.event_listener.association_product_model_draft_grid_after_listener:
        class: '%pim_datagrid.event_listener.add_parameters_to_product_grid.class%'
        arguments:
            - [dataLocale, product, associationType]
            - '@oro_datagrid.datagrid.request_params'
            - '@pim_catalog.context.catalog'
            - '@pim_user.context.user'
            - true
            - '@request_stack'
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.association-product-model-draft-grid, method: onBuildAfter }

    pim_enrich.event_listener.association_product_draft_grid_before_listener:
        class: '%pim_datagrid.event_listener.configure_product_grid_listener.class%'
        arguments:
            - '@pim_datagrid.datagrid.configuration.product.context_configurator'
            - '@pim_datagrid.datagrid.configuration.product.columns_configurator'
            - '@pim_datagrid.datagrid.configuration.product.filters_configurator'
            - '@pim_datagrid.datagrid.configuration.product.sorters_configurator'
            - '@pim_datagrid.datagrid.configuration.product.selected_attributes_configurator'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before.association-product-draft-grid, method: buildBefore }

    pim_enrich.event_listener.association_product_draft_grid_after_listener:
        class: '%pim_datagrid.event_listener.add_parameters_to_product_grid.class%'
        arguments:
            - [dataLocale, product, associationType]
            - '@oro_datagrid.datagrid.request_params'
            - '@pim_catalog.context.catalog'
            - '@pim_user.context.user'
            - true
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.association-product-draft-grid, method: onBuildAfter }