parameters:
    pcmt_connector.job.drafts_bulk_approve.name: 'job_drafts_bulk_approve'
    pcmt_connector.job.drafts_bulk_reject.name: 'job_drafts_bulk_reject'

services:
    pim_connector.job.xlsx_product_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%pim_connector.job_name.xlsx_product_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_connector.step.charset_validator'
                - '@pcmt_connector.step.xlsx_product_draft.import'
                - '@pim_connector.step.xlsx_product.import_associations'
        tags:
            - { name: akeneo_batch.job, connector: '%pim_connector.connector_name.xlsx%', type: '%pim_connector.job.import_type%' }

    pim_connector.job.xlsx_product_model_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%pim_connector.job_name.xlsx_product_model_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_connector.step.charset_validator'
                - '@pcmt_connector.step.xlsx_root_product_model.import'
                - '@pcmt_connector.step.xlsx_sub_product_model.import'
                - '@pim_connector.step.xlsx_compute_product_models_descendants.import'
                - '@pim_connector.step.xlsx_product_model.import_associations'
        tags:
            - { name: akeneo_batch.job, connector: '%pim_connector.connector_name.xlsx%', type: '%pim_connector.job.import_type%' }

    pcmt_connector.job.drafts_bulk_approve:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%pcmt_connector.job.drafts_bulk_approve.name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pcmt.step.drafts_bulk_approve'
        tags:
            - { name: akeneo_batch.job, connector: 'Pcmt Connector', type: '%pim_enrich.job.mass_edit_type%' }

    pcmt_connector.job.drafts_bulk_reject:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%pcmt_connector.job.drafts_bulk_reject.name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pcmt.step.drafts_bulk_reject'
        tags:
            - { name: akeneo_batch.job, connector: 'Pcmt Connector', type: '%pim_enrich.job.mass_edit_type%' }

