services:
    pim_datagrid.extension.pager.pager_resolver:
        class: '%pim_datagrid.extension.pager.pager_resolver.class%'
        arguments:
            - '@pim_datagrid.extension.pager.orm.pager'
            - '@oro_datagrid.extension.pager.dummy_pager'
            -
                - 'product-grid'
                - 'association-product-grid'
                - 'association-product-draft-grid'
                - 'association-product-model-grid'
                - 'association-product-model-draft-grid'
                - 'product-group-grid'
                - 'association-product-picker-grid'
                - 'published-product-grid'
                - 'proposal-grid'
