services:
    pcmt.connector.job.tasklet.drafts_bulk_approve:
        class: 'PcmtDraftBundle\Connector\Job\Tasklet\DraftsBulkApproveTasklet'
        autowire: true
        arguments:
            $constraintViolationNormalizer: '@pcmt_draft.normalizer.product_violation_with_label'

    pcmt.connector.job.tasklet.drafts_bulk_reject:
        class: 'PcmtDraftBundle\Connector\Job\Tasklet\DraftsBulkRejectTasklet'
        autowire: true
        arguments:
            $constraintViolationNormalizer: '@pcmt_draft.normalizer.product_violation_with_label'