######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

extensions:
    pcmt-product-drafts-edit:
        module: pim/form/common/edit-form

    pcmt-product-drafts-edit-form-breadcrumbs:
        module: pcmt/draft/common/breadcrumbs
        parent: pcmt-product-drafts-edit
        targetZone: breadcrumbs
        config:
            tab: pim-menu-products
            itemPath: identifier
            defaultLabel: pcmt_core.drafts_editing.new_product_draft.breadcrumb

    pcmt-product-drafts-edit-form-user-navigation:
        module: pim/menu/user-navigation
        parent: pcmt-product-drafts-edit
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pcmt-product-drafts-edit-form-main-image:
        module: pcmt/draft/common/main-image
        parent: pcmt-product-drafts-edit
        targetZone: main-image

    pcmt-product-drafts-edit-form-variant-navigation:
        module: pcmt/draft/form/variant-navigation
        parent: pcmt-product-drafts-edit
        targetZone: navigation

    pcmt-product-drafts-edit-form-cache-invalidator:
        module: pcmt/draft/form/cache-invalidator
        parent: pcmt-product-drafts-edit
        position: 1000

    pcmt-product-drafts-form-sequential-edit:
        module: pcmt/draft/form/sequential-edit
        parent: pcmt-product-drafts-edit
        targetZone: bottom-panel
        aclResourceId: pim_enrich_product_edit_attributes
        position: 100

    pcmt-product-drafts-edit-form-left-column:
        module: pim/form/common/column
        parent: pcmt-product-drafts-edit
        position: 5
        targetZone: column
        config:
            stateCode: product_edit_form
            navigationTitle: pim_menu.navigation.product

    pcmt-product-drafts-edit-form-column-tabs-navigation:
        module: pim/form/common/column-tabs-navigation
        parent: pcmt-product-drafts-edit-form-left-column
        targetZone: navigation
        position: 10
        config:
            title: pim_menu.navigation.product

    pcmt-product-drafts-edit-form-meta:
        module: pim/form/common/meta
        parent: pcmt-product-drafts-edit-form-left-column
        targetZone: bottom
        position: 10
        config:
            label: pim_menu.navigation.product_infos

    pcmt-product-drafts-edit-form-column-tabs:
        module: pim/form/common/column-tabs
        parent: pcmt-product-drafts-edit
        targetZone: content
        position: 100

    pcmt-product-drafts-edit-form-product-label:
        module: pcmt/draft/form/product-label
        parent: pcmt-product-drafts-edit
        targetZone: title
        position: 100

    pcmt-product-drafts-edit-form-product-completeness:
        module: pcmt/draft/form/product-completeness
        parent: pcmt-product-drafts-edit
        targetZone: meta
        position: 100

    pcmt-product-drafts-edit-form-total-missing-required-attributes:
        module: pcmt/draft/form/total-missing-required-attributes
        parent: pcmt-product-drafts-edit
        targetZone: meta
        position: 120

    pcmt-product-drafts-edit-form-save-buttons:
        module: pim/form/common/save-buttons
        parent: pcmt-product-drafts-edit
        targetZone: buttons
        position: 120

    pcmt-product-drafts-edit-form-save:
        module: pcmt/draft/form/save
        parent: pcmt-product-drafts-edit
        targetZone: buttons
        position: 0
        options:
            label: Save as draft

    pcmt-product-drafts-edit-form-state:
        module: pim/form/common/state
        parent: pcmt-product-drafts-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.product.label

    pcmt-product-drafts-edit-form-family:
        module: pcmt/draft/form/meta/family
        parent: pcmt-product-drafts-edit-form-meta
        targetZone: meta
        position: 70

    pcmt-product-drafts-edit-form-family-variant:
        module: pcmt/draft/form/meta/family-variant
        parent: pcmt-product-drafts-edit-form-meta
        targetZone: meta
        position: 75

    pcmt-product-drafts-edit-form-status-switcher:
        module: pcmt/draft/form/meta/status-switcher
        parent: pcmt-product-drafts-edit-form-meta
        targetZone: meta
        aclResourceId: pim_enrich_product_change_state
        position: 80

    pcmt-product-drafts-edit-form-created:
        module: pcmt/draft/form/meta/created
        parent: pcmt-product-drafts-edit-form-meta
        targetZone: meta
        position: 90
        config:
            label: pim_common.created
            labelBy: pim_common.by

    pcmt-product-drafts-edit-form-updated:
        module: pcmt/draft/form/meta/updated
        parent: pcmt-product-drafts-edit-form-meta
        targetZone: meta
        position: 100
        config:
            label: pim_enrich.entity.product.module.meta.updated
            labelBy: pim_common.by

    pcmt-product-drafts-edit-form-groups:
        module: pim/product-edit-form/meta/groups
        parent: pcmt-product-drafts-edit-form-meta
        targetZone: meta
        position: 110

    pcmt-product-drafts-edit-form-attributes:
        module: pcmt/draft/common/attributes
        parent: pcmt-product-drafts-edit-form-column-tabs
        targetZone: container
        aclResourceId: pim_enrich_product_edit_attributes
        position: 90
        config:
            removeAttributeRoute: pim_enrich_product_remove_attribute_rest
            removeAttributeACL: pim_enrich_product_remove_attribute
            tabTitle: pim_enrich.entity.attribute.plural_label
            deletionFailed: pim_enrich.entity.attribute.flash.delete.fail

    pcmt-product-drafts-edit-form-categories:
        module: pcmt/draft/form/categories
        parent: pcmt-product-drafts-edit-form-column-tabs
        targetZone: container
        aclResourceId: pim_enrich_product_categories_view
        position: 120
        config:
            itemCategoryListRoute: pim_enrich_product_listcategories
            itemCategoryTreeRoute: pcmt_draft_product_category_rest_list

    pcmt-product-drafts-edit-form-associations:
        module: pcmt/draft/form/associations
        parent: pcmt-product-drafts-edit-form-column-tabs
        targetZone: container
        aclResourceId: pim_enrich_associations_view
        position: 130
        config:
            aclAddAssociations: pim_enrich_associations_edit
            datagridName: 'association-product-draft-grid'

    pcmt-product-drafts-edit-form-comments:
        module: pcmt/product/form/comments
        parent: pcmt-product-drafts-edit-form-column-tabs
        targetZone: container
        aclResourceId: pim_enrich_product_comment
        position: 140

    pcmt-product-drafts-edit-form-attribute-group-selector:
        module: pcmt/draft/form/attributes/attribute-group-selector
        parent: pcmt-product-drafts-edit-form-attributes
        targetZone: other-actions
        position: 100

    pcmt-product-drafts-edit-form-attribute-filter:
        module: pim/product-edit-form/attribute-filter
        parent: pcmt-product-drafts-edit-form-attributes
        targetZone: other-actions
        position: 110

    pcmt-product-drafts-edit-form-attribute-filter-all:
        module: pim/product-edit-form/attribute-filter-all
        parent: pcmt-product-drafts-edit-form-attribute-filter
        position: 100

    pcmt-product-drafts-edit-form-attribute-filter-missing-required:
        module: pcmt/draft/form/attribute-filter-missing-required
        parent: pcmt-product-drafts-edit-form-attribute-filter
        position: 110


    pcmt-product-drafts-edit-form-attribute-filter-at-this-level-filter:
        module: pcmt/draft/form/attribute-filter-at-this-level
        parent: pcmt-product-drafts-edit-form-attribute-filter
        targetZone: self
        position: 120

    pcmt-product-drafts-edit-form-attribute-scope-switcher:
        module: pim/product-edit-form/scope-switcher
        parent: pcmt-product-drafts-edit
        targetZone: context
        position: 100
        config:
            context: base_product

    pcmt-product-drafts-edit-form-attribute-locale-switcher:
        module: pim/product-edit-form/locale-switcher
        parent: pcmt-product-drafts-edit
        targetZone: context
        position: 110
        config:
            context: base_product

    pcmt-product-drafts-edit-form-validation:
        module: pcmt/draft/form/attributes/validation
        parent: pcmt-product-drafts-edit-form-attributes
        targetZone: header
        position: 100

    pcmt-product-drafts-edit-form-read-only-parent-attributes:
        module: pcmt/draft/form/attributes/read-only-parent-attributes
        parent: pcmt-product-drafts-edit-form-attributes
        targetZone: self
        position: 100

    pcmt-product-drafts-edit-form-read-only-variant-axes:
        module: pcmt/draft/form/attributes/variant-axes
        parent: pcmt-product-drafts-edit-form-attributes
        targetZone: self
        position: 110

    pcmt-product-drafts-edit-form-locale-specific:
        module: pim/product-edit-form/attributes/locale-specific
        parent: pcmt-product-drafts-edit-form-attributes
        targetZone: self
        position: 100

    pcmt-product-drafts-edit-form-completeness-filter:
        module: pcmt/draft/form/attributes/completeness
        parent: pcmt-product-drafts-edit-form-attributes
        targetZone: self
        position: 100

    pcmt-product-drafts-edit-form-localizable:
        module: pim/product-edit-form/attributes/localizable
        parent: pcmt-product-drafts-edit-form-attributes
        targetZone: self
        position: 90

    pcmt-product-drafts-edit-form-label:
        module: pcmt/draft/form/label
        parent: pcmt-product-drafts-edit
        targetZone: state
        position: 10
        config:
            labels:
                createdDraft: pcmt_core.drafts_editing.labels.created_product_draft
                updatedDraft: pcmt_core.drafts_editing.labels.updated_draft

    pcmt-product-drafts-edit-form-attribute-description:
        module: dnd/product-edit-form/attributes/description
        parent: pcmt-product-drafts-edit-form-attributes
        targetZone: self
        position: 100

attribute_fields:
    akeneo-switch-field:           pim/boolean-field
    akeneo-datepicker-field:       pim/date-field
    akeneo-media-uploader-field:   pim/media-field
    akeneo-metric-field:           pim/metric-field
    akeneo-multi-select-field:     pim/multi-select-field
    akeneo-number-field:           pim/number-field
    akeneo-price-collection-field: pim/price-collection-field
    akeneo-simple-select-field:    pim/simple-select-field
    akeneo-text-field:             pim/text-field
    akeneo-textarea-field:         pim/textarea-field
    akeneo-wysiwyg-field:          pim/wysiwyg-field