######################################################################
# Copyright (c) 2020, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    pcmt.service.category_permissions_checker:
        class: PcmtSharedBundle\Service\Checker\CategoryPermissionsChecker

    pcmt.service.category_with_permissions_repository:
        class: PcmtSharedBundle\Service\CategoryWithPermissionsRepository
        autowire: true
