######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

custom_entities:
  gs1code:
    entity_class: PcmtCoreBundle\Entity\ReferenceData\GS1Codes\GS1Code