######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

parameters:
    pim_catalog.entity.attribute_translation.class: PcmtCoreBundle\Entity\AttributeTranslation

    pim_catalog.entity.attribute.class: PcmtCoreBundle\Entity\Attribute
    pim_catalog.repository.concatenated_attribute.class: PcmtCoreBundle\Entity\PcmtFamilyRepository

services:

    pcmt_catalog.repository.pcmt_family_concatenated_attribute:
        class: '%pim_catalog.repository.concatenated_attribute.class%'
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pim_catalog.entity.family.class%']
        tags:
            - { name: 'pim_repository' }

