######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    pcmt_enrichment.provider.form.product_job_instance:
        class: 'Akeneo\Platform\Bundle\ImportExportBundle\Provider\Form\JobInstanceFormProvider'
        arguments:
            -
                pcmt_e2open_export: pim-job-instance-pcmt-e2open-export
                pcmt_mst_supplier_export: pim-job-instance-pcmt-mst-supplier-export
                reference_data_import_xml: pcmt-reference-data-import
                reference_data_download_xmls: pcmt-simple-job
        tags:
            - { name: pim_enrich.provider.form, priority: 110 }