######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    PcmtCoreBundle\Command\Handler\PcmtReferenceDataDownloadHandler:
        autowire: true
        tags:
            - { name: 'console.command', command: 'pcmt:handler:download_reference_data' }


    PcmtCoreBundle\Command\Handler\PcmtReferenceDataImportHandler:
        autowire: true
        tags:
            - { name: 'console.command', command: 'pcmt:handler:import_reference_data' }