######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:
    pcmt_catalog.family.query.find_concatenated_attributes_for_family:
        class: PcmtCoreBundle\Query\FindConcatenatedAttributesForFamily
        autowire: true