######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

    pcmt_connector.save.reference_data:
        class: PcmtCoreBundle\Saver\ReferenceDataBulkSaver
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'

    pcmt.saver.product_through_draft:
        class: PcmtCoreBundle\Saver\ProductImportSaver
        arguments:
            - '@pim_catalog.saver.product'