######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

pcmt_permission_cis:
    type: action
    label: pcmt.permission.cis
    group_name: pcmt.permission.gdsn
