services:

    pim_datagrid.extension.formatter.property.datetime_property:
        class: 'PcmtCISBundle\Formatter\DateTimeProperty'
        arguments:
            - '@translator'
            - '@pim_catalog.localization.presenter.datetime'
            - '@pim_user.context.user'
        tags:
            - { name: oro_datagrid.extension.formatter.property, type: datetime }