extensions:

    pim-product-model-add-child-field-code:
        module: pcmt/form/common/fields/text-with-uuid-button
        config:
            required: true
            label: pim_common.code

    pim-product-model-add-child-field-text:
        module: pcmt/form/common/fields/values/text-with-uuid-button
        config:
            required: true
