extensions:
  pim-rules-profile-index:
    module: pim/common/simple-view
    config:
      template: pim/template/common/default-template

  pim-rules-profile-index-grid-container:
    module: pim/common/simple-view
    parent: pim-rules-profile-index
    targetZone: content
    config:
      template: pim/template/form/index/index

  pim-rules-profile-index-user-navigation:
    module: pim/menu/user-navigation
    parent: pim-rules-profile-index
    targetZone: user-menu
    config:
      userAccount: pim_menu.user.user_account
      logout: pim_menu.user.logout

  pim-rules-profile-index-grid-title:
    module: pim/common/grid-title
    parent: pim-rules-profile-index
    targetZone: title
    config:
      title: pcmt.entity.rules_profile.page_title.index

  pim-rules-profile-index-breadcrumbs:
    module: pim/common/breadcrumbs
    parent: pim-rules-profile-index
    targetZone: breadcrumbs
    config:
      tab: pim-menu-rules

  pim-rules-profile-index-filters-list:
    module: oro/datafilter/filters-list
    parent: pim-rules-profile-index-grid-container
    targetZone: filters

  pim-rules-profile-index-filters-manage:
    module: oro/datafilter/filters-button
    parent: pim-rules-profile-index-grid-container
    targetZone: filters

  pim-rules-profile-index-pagination:
    module: oro/datagrid/pagination-input
    parent: pim-rules-profile-index-grid-container
    targetZone: toolbar
    config:
      gridName: rules-profile-grid

  pim-rules-profile-index-grid:
    module: pim/form/common/index/grid
    parent: pim-rules-profile-index-grid-container
    position: 1000
    config:
      alias: rules-profile-grid
      metadata:
        jobType: rules

  pim-rules-profile-index-create-button:
    module: pim/form/common/index/create-button
    parent: pim-rules-profile-index
    targetZone: buttons
    position: 100
    aclResourceId: pcmt_permission_rules_create
    config:
      iconName:  plus
      title:     pcmt.entity.rules_profile.module.create.button
      modalForm: pim-rules-profile-create-modal
