######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

PcmtDraftBundle\Entity\NewProductDraft:
    type: entity
    repositoryClass: PcmtDraftBundle\Repository\DraftRepository