pcmt_rules_job_instance_rest_rules_get:
  path: /{identifier}
  defaults: { _controller: pcmt.controller.rest.rules_profile_job_instance:getRulesAction }
  methods: [GET]

pcmt_rules_job_instance_rest_rules_create:
  path: /
  defaults: { _controller: pcmt.controller.rest.rules_profile_job_instance:createRulesAction }
  methods: [POST]

pcmt_rules_job_instance_rest_rules_put:
  path: /{identifier}
  defaults: { _controller: pcmt.controller.rest.rules_profile_job_instance:putRulesAction }
  methods: [PUT, POST]

pcmt_rules_job_instance_rest_rules_delete:
  path: /{code}
  defaults: { _controller: pcmt.controller.rest.rules_profile_job_instance:deleteRulesAction }
  methods: [DELETE]

pcmt_rules_job_instance_rest_rules_launch:
    path: /{code}/launch
    defaults: { _controller: pcmt.controller.rest.rules_profile_job_instance:launchRulesAction }
    methods: [POST, GET]
