pcmt_rules_profile_index:
  path: /

pcmt_rules_profile_create:
  path: /create
  defaults: { _controller: pim_import_export.controller.import_profile:createAction }

pcmt_rules_profile_show:
  path: /{code}
  defaults: { _controller: pim_import_export.controller.import_profile:showAction }
  requirements:
    code: '[a-zA-Z0-9_]+'

pcmt_rules_profile_edit:
  path: /{code}/edit
  defaults: { _controller: pim_import_export.controller.import_profile:editAction }
  requirements:
    code: '[a-zA-Z0-9_]+'

pcmt_rules_profile_report:
  path: /{code}/reports
  defaults: { _controller: pim_import_export.controller.import_profile:reportAction }
  requirements:
    code: '[a-zA-Z0-9_]+'
