pcmt.rules.factory.job_notification:
    class: '%pim_import_export.factory.job_notification.class%'
    arguments:
        - ['rules']
        - '%pim_notification.entity.notification.class%'
    tags:
        - { name: pim_notification.factory.notification }