######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

  pcmt_rules.provider.form.rules_job_instance:
    class: 'Akeneo\Platform\Bundle\ImportExportBundle\Provider\Form\JobInstanceFormProvider'
    arguments:
      -
    tags:
      - { name: pim_enrich.provider.form, priority: 110 }
