services:

    pcmt.rules.job.default_values_provider.copy_products:
        class: PcmtRulesBundle\Connector\Job\DefaultValueProvider\CopyProductsDefaultValueProvider
        arguments:
            -
                - 'pcmt_copy_products_rule'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    pcmt.rules.job.default_values_provider.select_options:
        class: PcmtRulesBundle\Connector\Job\DefaultValueProvider\SelectOptionsDefaultValueProvider
        arguments:
            -
                - 'pcmt_select_options_rule'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    pcmt.rules.job.default_values_provider.pull_images:
        class: PcmtRulesBundle\Connector\Job\DefaultValueProvider\PullImagesDefaultValueProvider
        arguments:
            -
                - 'pcmt_pull_images_rule'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    pcmt.rules.job.default_values_provider.family_to_family:
        class: PcmtRulesBundle\Connector\Job\DefaultValueProvider\FamilyToFamilyDefaultValueProvider
        arguments:
            -
                - 'pcmt_family_to_family_rule'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }
