parameters:
    pcmt_permissions.check_user_access_to_the_category.tasklet_name: 'check_user_access_to_the_category'

services:
    pcmt_permissions.tasklet.check_user_access_to_the_category:
        class: 'PcmtPermissionsBundle\Connector\Job\Tasklet\CheckUserAccessToTheCategoryTasklet'
        arguments:
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.product_model'
            - '@pcmt.service.category_permissions_checker'

    pcmt_permissions.step.check_user_access_to_the_category:
        class: '%pim_connector.step.tasklet.class%'
        arguments:
            - '%pcmt_permissions.check_user_access_to_the_category.tasklet_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pcmt_permissions.tasklet.check_user_access_to_the_category'
