######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

PcmtCoreBundle\Entity\ReferenceData\TradeItemUnitDescriptorCode:
    type: entity
    repositoryClass: PcmtCoreBundle\Repository\GS1CodesRepository