######################################################################
# Copyright (c) 2019, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################

services:

  pcmt_connector.processor.denormalization.product:
    class: 'PcmtCustomDatasetBundle\Processor\Denormalizer\PcmtProductProcessor'
    arguments:
      - '@pim_catalog.repository.product'
      - '@pim_connector.processor.denormalization.product_to_import'
      - '@pim_catalog.entity_with_family_variant.add_parent_to_product'
      - '@pim_catalog.updater.product'
      - '@pim_catalog.validator.product'
      - '@akeneo_storage_utils.doctrine.object_detacher'
      - '@pim_catalog.comparator.filter.product'
      - '@pim_connector.processor.attribute_filter.product'
      - '@pim_connector.processor.denormalization.media_storer'

  pcmt_connector.processor.normalization.datagrid_view:
    class: '%pim_connector.processor.normalization.class%'
    arguments:
      - '@pcmt_connector.normalizer.datagrid_view'
      - '@akeneo_storage_utils.doctrine.object_detacher'

  pcmt_connector.processor.denormalization.datagrid_view:
    class: 'Akeneo\Tool\Component\Connector\Processor\Denormalization\Processor'
    arguments:
      - '@pim_datagrid.repository.datagrid_view'
      - '@pim_datagrid.factory.datagrid_view'
      - '@pcmt_connector.updater.datagrid_view'
      - '@validator'
      - '@akeneo_storage_utils.doctrine.object_detacher'